/* -*- C -*- */
/* @configure_input@ */

#ifndef		config_h_included
#define		config_h_included

/*************************************************************************
 * This section is automatically generated by 'configure'.  Adjust these
 * if configure didn't make a correct guess for your system.
 *************************************************************************/

/* Define if you have the <glob.h> header file. */
#undef HAVE_GLOB_H

/* Define if your <glob.h> defines GLOB_PERIOD macro. */
#undef HAVE_GLOB_PERIOD

/* Define if you already have a typedef for timer_t */
#undef HAVE_TIMER_T

/* Define if your struct utmp uses ut_user and not ut_name */
#undef HAVE_UTMAXTYPE

/* Define if your struct utmp has ut_host */
#undef HAVE_UT_UT_HOST

/* Define to `int' if <sys/types.h> doesn't define. */
#undef ino_t

/* Define to `mode_t' if <sys/types.h> doesn't define. */
#undef umode_t

/* Define if your system has _pw_stayopen variable (Irix specific?) */
#undef HAVE__PW_STAYOPEN

/* Define if you have the <syslog.h> header file. */
#undef HAVE_SYSLOG_H

/* Define if your <syslog.h> defines the LOG_CRON macro */
#undef HAVE_LOG_CRON

/* Define if your <syslog.h> defines the LOG_FTP macro */
#undef HAVE_LOG_FTP

@TOP@
/* autoheader generated things inserted here.  */
@BOTTOM@

#ifndef STDIN_FILENO
#define STDIN_FILENO 	0
#endif

#ifndef STDOUT_FILENO
#define STDOUT_FILENO 	1
#endif

#ifndef STDERR_FILENO
#define STDERR_FILENO	2
#endif

#endif /* config_h_included */
